export const SET_CURRENT_USER_REQUEST = "SET_CURRENT_USER_REQUEST"
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS"
export const SET_CURRENT_USER_FAILURE = "SET_CURRENT_USER_FAILURE"
export const SET_LOGOUT = "SET_LOGOUT"